[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mycalculatordapp = "HjpXgiRpxr3iJP9AeRxr6xzyqMMEUH5BzbfkUr8j1mTX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
